### ISSUE TITLE
Please update the csv with latest problems

### ISSUE THREAD

**Issue by snehasishroy** [fatliau/leetcode_MostLikedQuests#1]
Hi,

Thank you for creating the utility. Would it be possible for you to update the csv with latest problems?

**Comment by fatliau** [comment]
Working on it. Leetcode has update few field types in its json, which I will update it accordingly

**Comment by fatliau** [comment]
list has been refreshed to have 1746 rows now.

**Comment by snehasishroy** [comment]
Thank you very much for the prompt response. I never would have thought you would reply and update the repo so fast. Thank you again. Will start using your csv :)
